terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "> 1.1.0"
    }
  }
}


resource "local_file" "pet" {
  filename = each.value
  content  = var.content["statement1"]

  for_each = toset(var.filename)

  # count = length(var.filename)

  # lifecycle {
  #   create_before_destroy = true
  #   prevent_destroy = true
  # }

  depends_on = [
    random_pet.my-pet
  ]
}

# data "local_file" "dog" {
#   filename = "./root/dogs.txt"
# }


resource "random_pet" "my-pet" {
  prefix    = var.prefix[0]
  separator = var.separator
  length    = var.length
}

output "pet-name" {
  value       = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}
